// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM15uqRvcLkxcpYfPq1wXu5SudjcMQ30M',
    appId: '1:953663052528:web:0225571a984b77a9e48035',
    messagingSenderId: '953663052528',
    projectId: 'flutterisilo',
    authDomain: 'flutterisilo.firebaseapp.com',
    databaseURL: 'https://flutterisilo-default-rtdb.firebaseio.com',
    storageBucket: 'flutterisilo.appspot.com',
    measurementId: 'G-FHEH6Y4E8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcUIpwSfGue48I3C9cLpaNbvwVRPAs7XE',
    appId: '1:953663052528:android:2af83d2ec9085913e48035',
    messagingSenderId: '953663052528',
    projectId: 'flutterisilo',
    databaseURL: 'https://flutterisilo-default-rtdb.firebaseio.com',
    storageBucket: 'flutterisilo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcXdiXwAgZlICsR2EnyjRGPJDW07oyf_g',
    appId: '1:953663052528:ios:f3899b0c0e72dfd7e48035',
    messagingSenderId: '953663052528',
    projectId: 'flutterisilo',
    databaseURL: 'https://flutterisilo-default-rtdb.firebaseio.com',
    storageBucket: 'flutterisilo.appspot.com',
    iosClientId: '953663052528-js4f5vbvsnmfoo0nfujlfo2mvb06ma8s.apps.googleusercontent.com',
    iosBundleId: 'isilo.com.isilo',
  );
}
